package com.felhr.serialportexample.Controller;

import com.felhr.serialportexample.Controller.DatenObjekte;

public class DatenObjekteJob {

    public static int uiJobNr;
    public static byte ucJobTyp;
    public static byte ucUserNr;
    public static int uiKennNr;
    public static byte ucKennTyp;
    public static byte ucVerfahren;
    public static byte ucBetriebsArt;
    public static byte ucDrahtDurchm;
    public static byte ucGasTyp;
    public static byte ucWerkstoff;
    public static byte ucReglerTyp;
    public static byte ucGasVor;
    public static byte ucGasNach;
    public static byte ucEinSchlAbs;
    public static byte scEinSchlProz;
    public static byte ucUpSlope;
    public static byte ucDownSlope;
    public static byte ucZuendEgPrz;
    public static byte ucEndKraterPrz;
    public static byte ucFreiBrandPrz;
    public static byte ucFreiBrandKorr;
    public static byte ucSynBasis;
    public static byte scKorrPulsAmpl;
    public static byte scKorrDrossel;
    public static int uiPausenZeit;
    public static int uiPunktZeit;
    public static byte ucEinfaedeln;
    public static byte ucZuendDauer;
    public static byte ucEndKraDauer;
    public static byte ucPPOnOff;
    public static byte ucPPEnergie2;
    public static byte ucPPTime1;
    public static byte ucPPTime2;
    public static byte scPP_LBR_E2;
    public static int uiZuendStrom;
    public static int uiZuendSpann;
    public static int uiZuendEnergie;
    public static byte ucZuendDrossel;
    public static byte scZuendLBKorr;
    public static int uiStufe1Strom;
    public static int uiStufe1Spann;
    public static int uiStufe1Energie;
    public static byte ucStufe1Drossel;
    public static byte scStufe1LBKorr;
    public static int uiStufe2Strom;
    public static int uiStufe2Spann;
    public static int uiStufe2Energie;
    public static byte ucStufe2Drossel;
    public static byte scStufe2LBKorr;
    public static int uiStufe3Strom;
    public static int uiStufe3Spann;
    public static int uiStufe3Energie;
    public static byte ucStufe3Drossel;
    public static byte scStufe3LBKorr;
    public static int uiEndKraStrom;
    public static int uiEndKraSpann;
    public static int uiEndKraEnergie;
    public static byte ucEndKraDrossel;
    public static byte scEndKraLBKorr;
    public static int uiVorschubSet;
    public static int uiStromSet;
    public static int uiSpannungSet;
    public static int uiBlechSet;
    public static int uiElektrStromSet;
    public static byte ucHotStartDauer;
    public static byte ucHotStart;
    public static byte ucArcForce;
    public static byte ucElektrodeRI;
    public static int uiLimitEnergie;
    public static int uiLimitLbKorr;
    public static int uiStartAmplitude;
    public static byte ucStartZeit;
    public static byte ucStartUeberh;
    public static byte ucDrosselRI;
    public static byte ucUeberBlendZeit;
    public static byte ucDrossAbfall;
    public static byte ucMotorFlanke;
    public static byte ucDrossDynamic;
    public static byte ucLBR_Mode;
    public static byte ucBetriebMagAc;
    public static byte ucPosZeit;
    public static int uiNegZeit;
    public static byte ucKS_Erkenung;
    public static byte ucKS_Aufhebung;
    public static byte ucVerwZeitPN;
    public static byte ucVerwZeitNP;
    public static byte ucKaelteWert;
    public static byte ucStromSchwelle;
    public static int uiProtokollTyp;
    public static byte stJobBezZ1;
    public static byte stJobBezZ2;
    public static byte stJobBezZ3;
    public static byte stJobKomm;
    public static int uiJobCRC;

    public static void DataBase(){

        uiJobNr = (DatenObjekte.longArr[8]+(DatenObjekte.longArr[9])*256);
        ucJobTyp = (DatenObjekte.longArr[3]);
        ucUserNr = (DatenObjekte.longArr[4]);
        uiKennNr = (DatenObjekte.longArr[5])+(DatenObjekte.longArr[6]*256);
        ucKennTyp = (DatenObjekte.longArr[7]);
        ucVerfahren = (DatenObjekte.longArr[8]);
        ucBetriebsArt = (DatenObjekte.longArr[9]);
        ucDrahtDurchm = (DatenObjekte.longArr[10]);
        ucGasTyp = (DatenObjekte.longArr[11]);
        ucWerkstoff = (DatenObjekte.longArr[12]);
        ucReglerTyp = (DatenObjekte.longArr[13]);
        ucGasVor = (DatenObjekte.longArr[14]);
        ucGasNach = (DatenObjekte.longArr[15]);
        ucEinSchlAbs = (DatenObjekte.longArr[16]);
        scEinSchlProz = (DatenObjekte.longArr[17]);
        ucUpSlope = (DatenObjekte.longArr[18]);
        ucDownSlope = (DatenObjekte.longArr[19]);
        ucZuendEgPrz = (DatenObjekte.longArr[20]);
        ucEndKraterPrz = (DatenObjekte.longArr[21]);
        ucFreiBrandPrz = (DatenObjekte.longArr[22]);
        ucFreiBrandKorr = (DatenObjekte.longArr[23]);
        ucSynBasis = (DatenObjekte.longArr[24]);
        scKorrPulsAmpl = (DatenObjekte.longArr[25]);
        scKorrDrossel = (DatenObjekte.longArr[26]);
        uiPausenZeit = (DatenObjekte.longArr[27])+(DatenObjekte.longArr[28]*256);
        uiPunktZeit = (DatenObjekte.longArr[29])+(DatenObjekte.longArr[30]*256);
        ucEinfaedeln = (DatenObjekte.longArr[31]);
        ucZuendDauer = (DatenObjekte.longArr[32]);
        ucEndKraDauer = (DatenObjekte.longArr[33]);
        ucPPOnOff = (DatenObjekte.longArr[34]);
        ucPPEnergie2 = (DatenObjekte.longArr[35]);
        ucPPTime1 = (DatenObjekte.longArr[36]);
        ucPPTime2 = (DatenObjekte.longArr[37]);
        scPP_LBR_E2 = (DatenObjekte.longArr[38]);
        uiZuendStrom = (DatenObjekte.longArr[39])+(DatenObjekte.longArr[40]*256);
        uiZuendSpann = (DatenObjekte.longArr[41])+(DatenObjekte.longArr[42]*256);
        uiZuendEnergie = (DatenObjekte.longArr[43])+(DatenObjekte.longArr[44]*256);
        ucZuendDrossel = (DatenObjekte.longArr[45]);
        scZuendLBKorr = (DatenObjekte.longArr[46]);
        uiStufe1Strom = (DatenObjekte.longArr[47])+(DatenObjekte.longArr[48]*256);
        uiStufe1Spann = (DatenObjekte.longArr[49])+(DatenObjekte.longArr[50]*256);
        uiStufe1Energie = (DatenObjekte.longArr[51])+(DatenObjekte.longArr[52]*256);
        ucStufe1Drossel = (DatenObjekte.longArr[53]);
        scStufe1LBKorr = (DatenObjekte.longArr[54]);
        uiStufe2Strom = (DatenObjekte.longArr[55])+(DatenObjekte.longArr[56]*256);
        uiStufe2Spann = (DatenObjekte.longArr[57])+(DatenObjekte.longArr[58]*256);
        uiStufe2Energie = (DatenObjekte.longArr[59])+(DatenObjekte.longArr[60]*256);
        ucStufe2Drossel = (DatenObjekte.longArr[61]);
        scStufe2LBKorr = (DatenObjekte.longArr[62]);
        uiStufe3Strom = (DatenObjekte.longArr[63])+(DatenObjekte.longArr[64]*256);
        uiStufe3Spann = (DatenObjekte.longArr[65])+(DatenObjekte.longArr[66]*256);
        uiStufe3Energie = (DatenObjekte.longArr[67])+(DatenObjekte.longArr[68]*256);
        ucStufe3Drossel = (DatenObjekte.longArr[69]);
        scStufe3LBKorr = (DatenObjekte.longArr[70]);
        uiEndKraStrom = (DatenObjekte.longArr[71])+(DatenObjekte.longArr[72]*256);
        uiEndKraSpann = (DatenObjekte.longArr[73])+(DatenObjekte.longArr[74]*256);
        uiEndKraEnergie = (DatenObjekte.longArr[75])+(DatenObjekte.longArr[76]*256);
        ucEndKraDrossel = (DatenObjekte.longArr[77]);
        scEndKraLBKorr = (DatenObjekte.longArr[78]);
        uiVorschubSet = (DatenObjekte.longArr[79])+(DatenObjekte.longArr[80]*256);
        uiStromSet = (DatenObjekte.longArr[81])+(DatenObjekte.longArr[82]*256);
        uiSpannungSet = (DatenObjekte.longArr[83])+(DatenObjekte.longArr[84]*256);
        uiBlechSet = (DatenObjekte.longArr[85])+(DatenObjekte.longArr[86]*256);
        uiElektrStromSet = (DatenObjekte.longArr[87])+(DatenObjekte.longArr[88]*256);
        ucHotStartDauer = (DatenObjekte.longArr[89]);
        ucHotStart = (DatenObjekte.longArr[90]);
        ucArcForce = (DatenObjekte.longArr[91]);
        ucElektrodeRI = (DatenObjekte.longArr[92]);
        uiLimitEnergie = (DatenObjekte.longArr[93])+(DatenObjekte.longArr[94]*256);
        uiLimitLbKorr = (DatenObjekte.longArr[95])+(DatenObjekte.longArr[96]*256);
        uiStartAmplitude = (DatenObjekte.longArr[97])+(DatenObjekte.longArr[98]*256);
        ucStartZeit = (DatenObjekte.longArr[99]);
        ucStartUeberh = (DatenObjekte.longArr[100]);
        ucDrosselRI = (DatenObjekte.longArr[101]);
        ucUeberBlendZeit = (DatenObjekte.longArr[102]);
        ucDrossAbfall = (DatenObjekte.longArr[103]);
        ucMotorFlanke = (DatenObjekte.longArr[104]);
        ucDrossDynamic = (DatenObjekte.longArr[105]);
        ucLBR_Mode = (DatenObjekte.longArr[106]);
        ucBetriebMagAc = (DatenObjekte.longArr[107]);
        ucPosZeit = (DatenObjekte.longArr[108]);
        uiNegZeit = (DatenObjekte.longArr[109])+(DatenObjekte.longArr[110]*256);
        ucKS_Erkenung = (DatenObjekte.longArr[111]);
        ucKS_Aufhebung = (DatenObjekte.longArr[112]);
        ucVerwZeitPN = (DatenObjekte.longArr[113]);
        ucVerwZeitNP = (DatenObjekte.longArr[114]);
        ucKaelteWert = (DatenObjekte.longArr[115]);
        ucStromSchwelle = (DatenObjekte.longArr[116]);
        uiProtokollTyp = (DatenObjekte.longArr[117])+(DatenObjekte.longArr[118]*256);
        stJobBezZ1 = (DatenObjekte.longArr[119]);
        stJobBezZ2 = (DatenObjekte.longArr[135]);
        stJobBezZ3 = (DatenObjekte.longArr[151]);
        stJobKomm = (DatenObjekte.longArr[165]);
        uiJobCRC = (DatenObjekte.longArr[295])+(DatenObjekte.longArr[296]*256);
    }
}
